### PR TITLE
Set node version to up 9.10.0

### PR DESCRIPTION
**Pull request by miltoneiji**
```
error eslint@5.6.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0".
```

Just to make more clear that the node version should be >= 9.10.0

### CODE REVIEW

**Review by jgcmarins — CHANGES_REQUESTED** [review]
in fact, it should be LTS version: https://nodejs.org/en/blog/release/v8.9.0/

**Comment by jgcmarins** [comment]
even better: should be the same as react-native 8.3 https://github.com/facebook/react-native/blob/bd8b942ab9d265fa266dc4ae6bb00eabd2028698/package.json#L11

**Comment by miltoneiji** [comment]
@jgcmarins the problem is that `eslint@5.6.0` needs version `^6.14.0 || ^8.10.0 || >=9.10.0`.
So, it cannot be the LTS version (v8.9.0) neither react-native version (v8.3).

But since react-native accepts `>=8.3`, I think that 9.10.0 or greater should be ok, right?

**Comment by jgcmarins** [comment]
`^8.10.0` means that `v8.9.0` is ok
same for `>=8.3`
besides that, node foundation does not recommend versions above LTS

**Comment by miltoneiji** [comment]
Hmm thanks, I was not considering that `^8.10.0` matches `8.x.x` hahaha.
I fixed to `8.12.0`, that's the latest LTS version right now (https://nodejs.org/en/)

**Review by jgcmarins — APPROVED** [review]
hmm, in fact, I was wrong
`^8.10.0` does not stands for 8.x.x, my bad
we should consider [RN version](https://github.com/facebook/react-native/blob/bd8b942ab9d265fa266dc4ae6bb00eabd2028698/package.json#L11), since this package is related to RN
but if node LTS is on 8.12.0, we are good to go

**Comment by socksrust** [comment]
nice

**Pull request closed without merging**
